import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();


async function main() {
    console.log(`Start seeding ...`)
    const result = await prisma.t02_usuario.createMany({
        data:
            [
                {
                    t02_id: 14134,
                    t02_descricao: 'Ellen Martins Bogarim',
                    t02_tipo: '1',
                    t02_login: 'ellen.bogarim',
                    t02_senha: '12345E',
                    t02_empresa_id: 271,
                    t02_perfil_id: 2904,
                    t02_codigo_erp: '',
                    t02_email: 'guilherme.guarnieri@rioquality.com.br',
                    t02_telefone: '',
                    t02_sn_exibe_help_campos: 'S',
                    t02_googleapi: 'P',
                    t02_primeiro_acesso: 'N',
                    t02_ordem_colunas_form_cargas: null,
                    t02_data_hora_atualizacao: null,
                    t02_filial_expedicao_padrao: null,
                    t02_filiais_fatura_padrao: null,
                    t02_situacao: 1,
                    t02_faixa_valor: '',
                    t02_habilita_botao_ped_formar_carga: 'N',
                    t02_lang_user: null,
                    t02_envia_email_data_sincronizacao: 'N',
                    t02_perfil_transportadora: 'N'
                },
                {
                    t02_id: 11657,
                    t02_descricao: 'Valtencir da Silva Santos',
                    t02_tipo: '1',
                    t02_login: 'valtencir.santos',
                    t02_senha: '123Mudar',
                    t02_empresa_id: 271,
                    t02_perfil_id: 833,
                    t02_codigo_erp: '',
                    t02_email: 'valtencir.santos@rioquality.com.br',
                    t02_telefone: '',
                    t02_sn_exibe_help_campos: 'S',
                    t02_googleapi: 'P',
                    t02_primeiro_acesso: 'S',
                    t02_ordem_colunas_form_cargas: null,
                    t02_data_hora_atualizacao: null,
                    t02_filial_expedicao_padrao: null,
                    t02_filiais_fatura_padrao: null,
                    t02_situacao: 1,
                    t02_faixa_valor: '',
                    t02_habilita_botao_ped_formar_carga: 'N',
                    t02_lang_user: null,
                    t02_envia_email_data_sincronizacao: 'N',
                    t02_perfil_transportadora: 'N'
                },
                {
                    t02_id: 11581,
                    t02_descricao: 'Giovanna Silva',
                    t02_tipo: '',
                    t02_login: 'giovanna.silva',
                    t02_senha: 'G27811483',
                    t02_empresa_id: 271,
                    t02_perfil_id: 2904,
                    t02_codigo_erp: '',
                    t02_email: 'giovanna.silva@rioquality.com.br',
                    t02_telefone: '',
                    t02_sn_exibe_help_campos: 'S',
                    t02_googleapi: 'P',
                    t02_primeiro_acesso: 'N',
                    t02_ordem_colunas_form_cargas: null,
                    t02_data_hora_atualizacao: null,
                    t02_filial_expedicao_padrao: 3428,
                    t02_filiais_fatura_padrao: null,
                    t02_situacao: 1,
                    t02_faixa_valor: '',
                    t02_habilita_botao_ped_formar_carga: 'S',
                    t02_lang_user: 'en_US',
                    t02_envia_email_data_sincronizacao: 'N',
                    t02_perfil_transportadora: 'N'
                },
                {
                    t02_id: 2991,
                    t02_descricao: 'Administrador',
                    t02_tipo: '',
                    t02_login: 'rioquality',
                    t02_senha: '123Mudar',
                    t02_empresa_id: 271,
                    t02_perfil_id: 833,
                    t02_codigo_erp: '0',
                    t02_email: '.',
                    t02_telefone: '',
                    t02_sn_exibe_help_campos: 'S',
                    t02_googleapi: 'gme-creativesistemas',
                    t02_primeiro_acesso: 'N',
                    t02_ordem_colunas_form_cargas: '',
                    t02_data_hora_atualizacao: null,
                    t02_filial_expedicao_padrao: 3428,
                    t02_filiais_fatura_padrao: '',
                    t02_situacao: 1,
                    t02_faixa_valor: '',
                    t02_habilita_botao_ped_formar_carga: 'N',
                    t02_lang_user: null,
                    t02_envia_email_data_sincronizacao: 'N',
                    t02_perfil_transportadora: 'N'
                },
                {
                    t02_id: 3261,
                    t02_descricao: 'Administrador',
                    t02_tipo: '666',
                    t02_login: 'fusion.atv.rioquality',
                    t02_senha: 'Poi098)(*',
                    t02_empresa_id: 271,
                    t02_perfil_id: 833,
                    t02_codigo_erp: '',
                    t02_email: '',
                    t02_telefone: '',
                    t02_sn_exibe_help_campos: 'S',
                    t02_googleapi: 'gme-creativesistemas',
                    t02_primeiro_acesso: 'N',
                    t02_ordem_colunas_form_cargas: '',
                    t02_data_hora_atualizacao: null,
                    t02_filial_expedicao_padrao: null,
                    t02_filiais_fatura_padrao: '',
                    t02_situacao: 1,
                    t02_faixa_valor: '',
                    t02_habilita_botao_ped_formar_carga: 'N',
                    t02_lang_user: null,
                    t02_envia_email_data_sincronizacao: 'N',
                    t02_perfil_transportadora: 'N'
                },
                {
                    t02_id: 3947,
                    t02_descricao: 'Tiago Rosa',
                    t02_tipo: '1',
                    t02_login: 'tiago.rosa',
                    t02_senha: '123Mudar',
                    t02_empresa_id: 271,
                    t02_perfil_id: 1010,
                    t02_codigo_erp: '624',
                    t02_email: 'tiago.rosa@rioquality.com.br',
                    t02_telefone: '',
                    t02_sn_exibe_help_campos: 'S',
                    t02_googleapi: 'P',
                    t02_primeiro_acesso: 'S',
                    t02_ordem_colunas_form_cargas: '',
                    t02_data_hora_atualizacao: null,
                    t02_filial_expedicao_padrao: 3428,
                    t02_filiais_fatura_padrao: '',
                    t02_situacao: 1,
                    t02_faixa_valor: '',
                    t02_habilita_botao_ped_formar_carga: 'N',
                    t02_lang_user: null,
                    t02_envia_email_data_sincronizacao: 'N',
                    t02_perfil_transportadora: 'N'
                },
                {
                    t02_id: 4273,
                    t02_descricao: 'donato.meirelles',
                    t02_tipo: '1',
                    t02_login: 'donato.meirelles',
                    t02_senha: 'RX78gundam!!',
                    t02_empresa_id: 271,
                    t02_perfil_id: 833,
                    t02_codigo_erp: '',
                    t02_email: 'donato.meirelles@rioquality.com.br',
                    t02_telefone: '',
                    t02_sn_exibe_help_campos: 'S',
                    t02_googleapi: 'P',
                    t02_primeiro_acesso: 'N',
                    t02_ordem_colunas_form_cargas: '',
                    t02_data_hora_atualizacao: null,
                    t02_filial_expedicao_padrao: null,
                    t02_filiais_fatura_padrao: '',
                    t02_situacao: 1,
                    t02_faixa_valor: '',
                    t02_habilita_botao_ped_formar_carga: 'N',
                    t02_lang_user: null,
                    t02_envia_email_data_sincronizacao: 'N',
                    t02_perfil_transportadora: 'N'
                },
                {
                    t02_id: 5327,
                    t02_descricao: 'Fabiana Santos',
                    t02_tipo: '',
                    t02_login: 'fabiana.santos',
                    t02_senha: 'Soumagra.22',
                    t02_empresa_id: 271,
                    t02_perfil_id: 1151,
                    t02_codigo_erp: '',
                    t02_email: 'fabiana.santos@rioquality.com.br',
                    t02_telefone: '',
                    t02_sn_exibe_help_campos: 'S',
                    t02_googleapi: 'P',
                    t02_primeiro_acesso: 'N',
                    t02_ordem_colunas_form_cargas: '',
                    t02_data_hora_atualizacao: null,
                    t02_filial_expedicao_padrao: 3428,
                    t02_filiais_fatura_padrao: '',
                    t02_situacao: 1,
                    t02_faixa_valor: '',
                    t02_habilita_botao_ped_formar_carga: 'N',
                    t02_lang_user: null,
                    t02_envia_email_data_sincronizacao: 'N',
                    t02_perfil_transportadora: 'N'
                },
                {
                    t02_id: 9043,
                    t02_descricao: 'Leonardo Parada ',
                    t02_tipo: '',
                    t02_login: 'leonardo.guimaraes',
                    t02_senha: '123Mudar',
                    t02_empresa_id: 271,
                    t02_perfil_id: 957,
                    t02_codigo_erp: '',
                    t02_email: 'rioquality',
                    t02_telefone: '',
                    t02_sn_exibe_help_campos: 'S',
                    t02_googleapi: 'P',
                    t02_primeiro_acesso: 'N',
                    t02_ordem_colunas_form_cargas: '',
                    t02_data_hora_atualizacao: null,
                    t02_filial_expedicao_padrao: null,
                    t02_filiais_fatura_padrao: '',
                    t02_situacao: 1,
                    t02_faixa_valor: '',
                    t02_habilita_botao_ped_formar_carga: 'N',
                    t02_lang_user: null,
                    t02_envia_email_data_sincronizacao: 'N',
                    t02_perfil_transportadora: 'N'
                },
                {
                    t02_id: 4674,
                    t02_descricao: 'Coordenador',
                    t02_tipo: '',
                    t02_login: 'coordenador',
                    t02_senha: '123Mudar',
                    t02_empresa_id: 271,
                    t02_perfil_id: 1151,
                    t02_codigo_erp: '',
                    t02_email: '',
                    t02_telefone: '',
                    t02_sn_exibe_help_campos: 'S',
                    t02_googleapi: 'P',
                    t02_primeiro_acesso: 'N',
                    t02_ordem_colunas_form_cargas: '',
                    t02_data_hora_atualizacao: null,
                    t02_filial_expedicao_padrao: null,
                    t02_filiais_fatura_padrao: '3428',
                    t02_situacao: 1,
                    t02_faixa_valor: '',
                    t02_habilita_botao_ped_formar_carga: 'N',
                    t02_lang_user: null,
                    t02_envia_email_data_sincronizacao: 'N',
                    t02_perfil_transportadora: 'N'
                },
                {
                    t02_id: 4278,
                    t02_descricao: 'carolina.nazareth',
                    t02_tipo: '',
                    t02_login: 'carolina.nazareth',
                    t02_senha: '123Mudar',
                    t02_empresa_id: 271,
                    t02_perfil_id: 2721,
                    t02_codigo_erp: '',
                    t02_email: 'carolina.nazareth@rioquality.com.br',
                    t02_telefone: '',
                    t02_sn_exibe_help_campos: 'S',
                    t02_googleapi: 'P',
                    t02_primeiro_acesso: 'N',
                    t02_ordem_colunas_form_cargas: '',
                    t02_data_hora_atualizacao: null,
                    t02_filial_expedicao_padrao: null,
                    t02_filiais_fatura_padrao: null,
                    t02_situacao: 1,
                    t02_faixa_valor: '',
                    t02_habilita_botao_ped_formar_carga: 'N',
                    t02_lang_user: null,
                    t02_envia_email_data_sincronizacao: 'N',
                    t02_perfil_transportadora: 'N'
                },
                {
                    t02_id: 4280,
                    t02_descricao: 'vitor.francisco',
                    t02_tipo: '',
                    t02_login: 'vitor.francisco',
                    t02_senha: '123Mudar',
                    t02_empresa_id: 271,
                    t02_perfil_id: 2721,
                    t02_codigo_erp: '',
                    t02_email: 'vitor.francisco@rioquality.com.br',
                    t02_telefone: '',
                    t02_sn_exibe_help_campos: 'S',
                    t02_googleapi: 'P',
                    t02_primeiro_acesso: 'S',
                    t02_ordem_colunas_form_cargas: '',
                    t02_data_hora_atualizacao: null,
                    t02_filial_expedicao_padrao: null,
                    t02_filiais_fatura_padrao: null,
                    t02_situacao: 1,
                    t02_faixa_valor: '',
                    t02_habilita_botao_ped_formar_carga: 'N',
                    t02_lang_user: null,
                    t02_envia_email_data_sincronizacao: 'N',
                    t02_perfil_transportadora: 'N'
                },
                {
                    t02_id: 9251,
                    t02_descricao: 'Rafael Oliveira ',
                    t02_tipo: '',
                    t02_login: 'rafael.oliveiraa',
                    t02_senha: '1987Rafa',
                    t02_empresa_id: 271,
                    t02_perfil_id: 956,
                    t02_codigo_erp: '253',
                    t02_email: 'rafael.oliveira@rioquality.com.br',
                    t02_telefone: '',
                    t02_sn_exibe_help_campos: 'S',
                    t02_googleapi: 'P',
                    t02_primeiro_acesso: 'N',
                    t02_ordem_colunas_form_cargas: '',
                    t02_data_hora_atualizacao: null,
                    t02_filial_expedicao_padrao: 3428,
                    t02_filiais_fatura_padrao: null,
                    t02_situacao: 1,
                    t02_faixa_valor: '',
                    t02_habilita_botao_ped_formar_carga: 'S',
                    t02_lang_user: null,
                    t02_envia_email_data_sincronizacao: 'N',
                    t02_perfil_transportadora: 'N'
                },
                {
                    t02_id: 8946,
                    t02_descricao: 'Eduardo de Oliveira',
                    t02_tipo: '',
                    t02_login: 'eduardo.verdan',
                    t02_senha: 'Ed170404',
                    t02_empresa_id: 271,
                    t02_perfil_id: 2740,
                    t02_codigo_erp: '',
                    t02_email: 'rioquality',
                    t02_telefone: '',
                    t02_sn_exibe_help_campos: 'S',
                    t02_googleapi: 'P',
                    t02_primeiro_acesso: 'N',
                    t02_ordem_colunas_form_cargas: '',
                    t02_data_hora_atualizacao: null,
                    t02_filial_expedicao_padrao: null,
                    t02_filiais_fatura_padrao: null,
                    t02_situacao: 1,
                    t02_faixa_valor: '',
                    t02_habilita_botao_ped_formar_carga: 'N',
                    t02_lang_user: null,
                    t02_envia_email_data_sincronizacao: 'N',
                    t02_perfil_transportadora: 'N'
                },
                {
                    t02_id: 5884,
                    t02_descricao: 'Thor - Fusion',
                    t02_tipo: '',
                    t02_login: 'thor.rioquality',
                    t02_senha: 'Thor#@!3',
                    t02_empresa_id: 271,
                    t02_perfil_id: 833,
                    t02_codigo_erp: '',
                    t02_email: '',
                    t02_telefone: '',
                    t02_sn_exibe_help_campos: 'S',
                    t02_googleapi: 'P',
                    t02_primeiro_acesso: 'N',
                    t02_ordem_colunas_form_cargas: '',
                    t02_data_hora_atualizacao: null,
                    t02_filial_expedicao_padrao: null,
                    t02_filiais_fatura_padrao: null,
                    t02_situacao: 0,
                    t02_faixa_valor: '',
                    t02_habilita_botao_ped_formar_carga: 'N',
                    t02_lang_user: null,
                    t02_envia_email_data_sincronizacao: 'N',
                    t02_perfil_transportadora: 'N'
                },
                {
                    t02_id: 3727,
                    t02_descricao: 'Paulo Marinho',
                    t02_tipo: '',
                    t02_login: 'paulo.marinho',
                    t02_senha: 'Paul1201',
                    t02_empresa_id: 271,
                    t02_perfil_id: 833,
                    t02_codigo_erp: '0',
                    t02_email: 'paulo.marinho@rioquality.com.br',
                    t02_telefone: '',
                    t02_sn_exibe_help_campos: 'S',
                    t02_googleapi: 'P',
                    t02_primeiro_acesso: 'N',
                    t02_ordem_colunas_form_cargas: '',
                    t02_data_hora_atualizacao: null,
                    t02_filial_expedicao_padrao: 3428,
                    t02_filiais_fatura_padrao: null,
                    t02_situacao: 1,
                    t02_faixa_valor: '',
                    t02_habilita_botao_ped_formar_carga: 'S',
                    t02_lang_user: null,
                    t02_envia_email_data_sincronizacao: 'N',
                    t02_perfil_transportadora: 'N'
                },
                {
                    t02_id: 3726,
                    t02_descricao: 'Guilherme Guarnieri',
                    t02_tipo: '',
                    t02_login: 'guilherme.guarnieri',
                    t02_senha: 'Guil0520',
                    t02_empresa_id: 271,
                    t02_perfil_id: 833,
                    t02_codigo_erp: '17',
                    t02_email: 'guilherme.guarnieri@rioquality.com.br',
                    t02_telefone: '21993840914',
                    t02_sn_exibe_help_campos: 'S',
                    t02_googleapi: 'P',
                    t02_primeiro_acesso: 'N',
                    t02_ordem_colunas_form_cargas: '',
                    t02_data_hora_atualizacao: null,
                    t02_filial_expedicao_padrao: 3428,
                    t02_filiais_fatura_padrao: null,
                    t02_situacao: 1,
                    t02_faixa_valor: '',
                    t02_habilita_botao_ped_formar_carga: 'S',
                    t02_lang_user: null,
                    t02_envia_email_data_sincronizacao: 'N',
                    t02_perfil_transportadora: 'N'
                },
                {
                    t02_id: 4274,
                    t02_descricao: 'daniel.messias',
                    t02_tipo: '',
                    t02_login: 'daniel.messias',
                    t02_senha: 'Leinad24011983',
                    t02_empresa_id: 271,
                    t02_perfil_id: 2740,
                    t02_codigo_erp: '',
                    t02_email: 'daniel.messias@rioquality.com.br',
                    t02_telefone: '',
                    t02_sn_exibe_help_campos: 'S',
                    t02_googleapi: 'P',
                    t02_primeiro_acesso: 'N',
                    t02_ordem_colunas_form_cargas: '',
                    t02_data_hora_atualizacao: null,
                    t02_filial_expedicao_padrao: null,
                    t02_filiais_fatura_padrao: null,
                    t02_situacao: 1,
                    t02_faixa_valor: '',
                    t02_habilita_botao_ped_formar_carga: 'N',
                    t02_lang_user: null,
                    t02_envia_email_data_sincronizacao: 'N',
                    t02_perfil_transportadora: 'N'
                },
                {
                    t02_id: 4279,
                    t02_descricao: 'valdeir.degani',
                    t02_tipo: '',
                    t02_login: 'valdeir.degani',
                    t02_senha: 'Degani1436',
                    t02_empresa_id: 271,
                    t02_perfil_id: 957,
                    t02_codigo_erp: '',
                    t02_email: 'valdeir.degani@rioquality.com.br',
                    t02_telefone: '',
                    t02_sn_exibe_help_campos: 'S',
                    t02_googleapi: 'P',
                    t02_primeiro_acesso: 'N',
                    t02_ordem_colunas_form_cargas: '',
                    t02_data_hora_atualizacao: null,
                    t02_filial_expedicao_padrao: null,
                    t02_filiais_fatura_padrao: null,
                    t02_situacao: 1,
                    t02_faixa_valor: '',
                    t02_habilita_botao_ped_formar_carga: 'N',
                    t02_lang_user: null,
                    t02_envia_email_data_sincronizacao: 'N',
                    t02_perfil_transportadora: 'N'
                },
                {
                    t02_id: 7233,
                    t02_descricao: 'Marlon Julio Leocadio',
                    t02_tipo: '',
                    t02_login: 'marlon.leocadio',
                    t02_senha: 'rQ38871732mjL',
                    t02_empresa_id: 271,
                    t02_perfil_id: 1010,
                    t02_codigo_erp: '1054',
                    t02_email: 'marlon.leocadio@rioquality.com.br',
                    t02_telefone: '',
                    t02_sn_exibe_help_campos: 'S',
                    t02_googleapi: 'P',
                    t02_primeiro_acesso: 'N',
                    t02_ordem_colunas_form_cargas: '',
                    t02_data_hora_atualizacao: null,
                    t02_filial_expedicao_padrao: null,
                    t02_filiais_fatura_padrao: null,
                    t02_situacao: 1,
                    t02_faixa_valor: '',
                    t02_habilita_botao_ped_formar_carga: 'S',
                    t02_lang_user: null,
                    t02_envia_email_data_sincronizacao: 'N',
                    t02_perfil_transportadora: 'N'
                },
                {
                    t02_id: 8094,
                    t02_descricao: 'Felipe Alexandre da Silva Augusto Para',
                    t02_tipo: '',
                    t02_login: 'felipe.para',
                    t02_senha: 'Sept1337',
                    t02_empresa_id: 271,
                    t02_perfil_id: 3090,
                    t02_codigo_erp: '',
                    t02_email: 'guilherme.guarnieri',
                    t02_telefone: '',
                    t02_sn_exibe_help_campos: 'S',
                    t02_googleapi: 'P',
                    t02_primeiro_acesso: 'N',
                    t02_ordem_colunas_form_cargas: '',
                    t02_data_hora_atualizacao: null,
                    t02_filial_expedicao_padrao: null,
                    t02_filiais_fatura_padrao: null,
                    t02_situacao: 1,
                    t02_faixa_valor: '',
                    t02_habilita_botao_ped_formar_carga: 'N',
                    t02_lang_user: null,
                    t02_envia_email_data_sincronizacao: 'N',
                    t02_perfil_transportadora: 'N'
                },
                {
                    t02_id: 5486,
                    t02_descricao: 'Thiago - Thor',
                    t02_tipo: '1',
                    t02_login: 'thiago.rioquality',
                    t02_senha: 'cl@r0_92oo8646',
                    t02_empresa_id: 271,
                    t02_perfil_id: 833,
                    t02_codigo_erp: '',
                    t02_email: '',
                    t02_telefone: '',
                    t02_sn_exibe_help_campos: 'S',
                    t02_googleapi: 'P',
                    t02_primeiro_acesso: 'N',
                    t02_ordem_colunas_form_cargas: '',
                    t02_data_hora_atualizacao: null,
                    t02_filial_expedicao_padrao: null,
                    t02_filiais_fatura_padrao: '',
                    t02_situacao: 1,
                    t02_faixa_valor: '',
                    t02_habilita_botao_ped_formar_carga: 'N',
                    t02_lang_user: null,
                    t02_envia_email_data_sincronizacao: 'N',
                    t02_perfil_transportadora: 'N'
                },
                {
                    t02_id: 9487,
                    t02_descricao: 'Vendedor',
                    t02_tipo: '1',
                    t02_login: 'vendedor',
                    t02_senha: '123Mudar',
                    t02_empresa_id: 271,
                    t02_perfil_id: 1151,
                    t02_codigo_erp: '',
                    t02_email: '',
                    t02_telefone: '',
                    t02_sn_exibe_help_campos: 'S',
                    t02_googleapi: 'P',
                    t02_primeiro_acesso: 'N',
                    t02_ordem_colunas_form_cargas: '',
                    t02_data_hora_atualizacao: null,
                    t02_filial_expedicao_padrao: null,
                    t02_filiais_fatura_padrao: '',
                    t02_situacao: 1,
                    t02_faixa_valor: '',
                    t02_habilita_botao_ped_formar_carga: 'N',
                    t02_lang_user: null,
                    t02_envia_email_data_sincronizacao: 'N',
                    t02_perfil_transportadora: 'N'
                },
                {
                    t02_id: 4277,
                    t02_descricao: 'anaina.guarnieri',
                    t02_tipo: '',
                    t02_login: 'anaina.guarnieri',
                    t02_senha: 'Amg152027',
                    t02_empresa_id: 271,
                    t02_perfil_id: 2721,
                    t02_codigo_erp: '',
                    t02_email: 'anaina.guarnieri@rioquality.com.br',
                    t02_telefone: '',
                    t02_sn_exibe_help_campos: 'S',
                    t02_googleapi: 'P',
                    t02_primeiro_acesso: 'N',
                    t02_ordem_colunas_form_cargas: '',
                    t02_data_hora_atualizacao: null,
                    t02_filial_expedicao_padrao: null,
                    t02_filiais_fatura_padrao: null,
                    t02_situacao: 1,
                    t02_faixa_valor: '',
                    t02_habilita_botao_ped_formar_carga: 'N',
                    t02_lang_user: null,
                    t02_envia_email_data_sincronizacao: 'N',
                    t02_perfil_transportadora: 'N'
                },
                {
                    t02_id: 2992,
                    t02_descricao: 'Administrador',
                    t02_tipo: '666',
                    t02_login: 'fusion.rioquality',
                    t02_senha: 'Qwe123!@#',
                    t02_empresa_id: 271,
                    t02_perfil_id: 833,
                    t02_codigo_erp: '0',
                    t02_email: '0',
                    t02_telefone: '',
                    t02_sn_exibe_help_campos: 'S',
                    t02_googleapi: 'gme-creativesistemas',
                    t02_primeiro_acesso: 'N',
                    t02_ordem_colunas_form_cargas: '',
                    t02_data_hora_atualizacao: null,
                    t02_filial_expedicao_padrao: 3428,
                    t02_filiais_fatura_padrao: '',
                    t02_situacao: 1,
                    t02_faixa_valor: '',
                    t02_habilita_botao_ped_formar_carga: 'N',
                    t02_lang_user: null,
                    t02_envia_email_data_sincronizacao: 'N',
                    t02_perfil_transportadora: 'N'
                },
                {
                    t02_id: 13232,
                    t02_descricao: 'Julyanna Ruiz',
                    t02_tipo: '',
                    t02_login: 'julyanna.ruiz',
                    t02_senha: 'J185877a',
                    t02_empresa_id: 271,
                    t02_perfil_id: 2904,
                    t02_codigo_erp: '',
                    t02_email: 'guilherme.guarnieri@rioquality.com.br',
                    t02_telefone: '',
                    t02_sn_exibe_help_campos: 'S',
                    t02_googleapi: 'P',
                    t02_primeiro_acesso: 'N',
                    t02_ordem_colunas_form_cargas: null,
                    t02_data_hora_atualizacao: null,
                    t02_filial_expedicao_padrao: 3428,
                    t02_filiais_fatura_padrao: null,
                    t02_situacao: 1,
                    t02_faixa_valor: '',
                    t02_habilita_botao_ped_formar_carga: 'N',
                    t02_lang_user: null,
                    t02_envia_email_data_sincronizacao: 'N',
                    t02_perfil_transportadora: 'N'
                },
                {
                    t02_id: 12391,
                    t02_descricao: 'Caique Duarte Oliveira ',
                    t02_tipo: '',
                    t02_login: 'caique.oliveira',
                    t02_senha: 'N@rutodbz1',
                    t02_empresa_id: 271,
                    t02_perfil_id: 2740,
                    t02_codigo_erp: '',
                    t02_email: 'caique.oliveira@rioquality.com.br',
                    t02_telefone: '',
                    t02_sn_exibe_help_campos: 'S',
                    t02_googleapi: 'P',
                    t02_primeiro_acesso: 'N',
                    t02_ordem_colunas_form_cargas: null,
                    t02_data_hora_atualizacao: null,
                    t02_filial_expedicao_padrao: 3428,
                    t02_filiais_fatura_padrao: null,
                    t02_situacao: 1,
                    t02_faixa_valor: '',
                    t02_habilita_botao_ped_formar_carga: 'N',
                    t02_lang_user: null,
                    t02_envia_email_data_sincronizacao: 'N',
                    t02_perfil_transportadora: 'N'
                },
                {
                    t02_id: 12356,
                    t02_descricao: 'Gisane Pacheco da Cunha',
                    t02_tipo: '',
                    t02_login: 'gisane.cunha',
                    t02_senha: 'Guilherme0215',
                    t02_empresa_id: 271,
                    t02_perfil_id: 3090,
                    t02_codigo_erp: '',
                    t02_email: 'gisane.cunha@rioquality.com.br',
                    t02_telefone: '',
                    t02_sn_exibe_help_campos: 'S',
                    t02_googleapi: 'P',
                    t02_primeiro_acesso: 'N',
                    t02_ordem_colunas_form_cargas: null,
                    t02_data_hora_atualizacao: null,
                    t02_filial_expedicao_padrao: null,
                    t02_filiais_fatura_padrao: null,
                    t02_situacao: 1,
                    t02_faixa_valor: '',
                    t02_habilita_botao_ped_formar_carga: 'N',
                    t02_lang_user: 'en_US',
                    t02_envia_email_data_sincronizacao: 'N',
                    t02_perfil_transportadora: 'N'
                },
                {
                    t02_id: 12574,
                    t02_descricao: 'Lucio Mauro Oliveira Benedito',
                    t02_tipo: '',
                    t02_login: 'lucio.benedito',
                    t02_senha: 'Luc9412*',
                    t02_empresa_id: 271,
                    t02_perfil_id: 833,
                    t02_codigo_erp: '',
                    t02_email: 'lucio.benedito@rioquality.com.br',
                    t02_telefone: '',
                    t02_sn_exibe_help_campos: 'S',
                    t02_googleapi: 'P',
                    t02_primeiro_acesso: 'N',
                    t02_ordem_colunas_form_cargas: null,
                    t02_data_hora_atualizacao: null,
                    t02_filial_expedicao_padrao: 3428,
                    t02_filiais_fatura_padrao: null,
                    t02_situacao: 1,
                    t02_faixa_valor: '',
                    t02_habilita_botao_ped_formar_carga: 'S',
                    t02_lang_user: null,
                    t02_envia_email_data_sincronizacao: 'N',
                    t02_perfil_transportadora: 'N'
                },
                {
                    t02_id: 14248,
                    t02_descricao: 'Angela Maria Esperandio',
                    t02_tipo: '',
                    t02_login: 'angela.maria',
                    t02_senha: 'Amev-123',
                    t02_empresa_id: 271,
                    t02_perfil_id: 2904,
                    t02_codigo_erp: '',
                    t02_email: 'guilherme.guarnieri@rioquality.com.br',
                    t02_telefone: '21993840914',
                    t02_sn_exibe_help_campos: 'S',
                    t02_googleapi: 'P',
                    t02_primeiro_acesso: 'N',
                    t02_ordem_colunas_form_cargas: null,
                    t02_data_hora_atualizacao: null,
                    t02_filial_expedicao_padrao: null,
                    t02_filiais_fatura_padrao: null,
                    t02_situacao: 1,
                    t02_faixa_valor: '',
                    t02_habilita_botao_ped_formar_carga: 'N',
                    t02_lang_user: 'en_US',
                    t02_envia_email_data_sincronizacao: 'N',
                    t02_perfil_transportadora: 'N'
                },
                {
                    t02_id: 11590,
                    t02_descricao: 'Daniela Coutinho Arruda',
                    t02_tipo: '',
                    t02_login: 'daniela.arruda',
                    t02_senha: '019868D',
                    t02_empresa_id: 271,
                    t02_perfil_id: 3091,
                    t02_codigo_erp: '',
                    t02_email: 'daniela.arruda@rioquality.com.br',
                    t02_telefone: '',
                    t02_sn_exibe_help_campos: 'S',
                    t02_googleapi: 'P',
                    t02_primeiro_acesso: 'N',
                    t02_ordem_colunas_form_cargas: null,
                    t02_data_hora_atualizacao: null,
                    t02_filial_expedicao_padrao: null,
                    t02_filiais_fatura_padrao: null,
                    t02_situacao: 1,
                    t02_faixa_valor: '',
                    t02_habilita_botao_ped_formar_carga: 'N',
                    t02_lang_user: null,
                    t02_envia_email_data_sincronizacao: 'N',
                    t02_perfil_transportadora: 'N'
                },
                {
                    t02_id: 4272,
                    t02_descricao: 'Joelson Queiroz',
                    t02_tipo: '',
                    t02_login: 'joelson.queiroz',
                    t02_senha: '2002Mae',
                    t02_empresa_id: 271,
                    t02_perfil_id: 3090,
                    t02_codigo_erp: '1029',
                    t02_email: 'joelson.queiroz@rioquality.com.br',
                    t02_telefone: '',
                    t02_sn_exibe_help_campos: 'S',
                    t02_googleapi: 'P',
                    t02_primeiro_acesso: 'N',
                    t02_ordem_colunas_form_cargas: '',
                    t02_data_hora_atualizacao: null,
                    t02_filial_expedicao_padrao: 3428,
                    t02_filiais_fatura_padrao: null,
                    t02_situacao: 1,
                    t02_faixa_valor: '',
                    t02_habilita_botao_ped_formar_carga: 'N',
                    t02_lang_user: null,
                    t02_envia_email_data_sincronizacao: 'N',
                    t02_perfil_transportadora: 'N'
                },
                {
                    t02_id: 14249,
                    t02_descricao: 'Larissa Farias Lucena',
                    t02_tipo: '1',
                    t02_login: 'larissa.farias',
                    t02_senha: 'Lari7588',
                    t02_empresa_id: 271,
                    t02_perfil_id: 3090,
                    t02_codigo_erp: '',
                    t02_email: 'guilherme.guarnieri@rioquality.com.br',
                    t02_telefone: '21993840914',
                    t02_sn_exibe_help_campos: 'S',
                    t02_googleapi: 'P',
                    t02_primeiro_acesso: 'N',
                    t02_ordem_colunas_form_cargas: null,
                    t02_data_hora_atualizacao: null,
                    t02_filial_expedicao_padrao: null,
                    t02_filiais_fatura_padrao: null,
                    t02_situacao: 1,
                    t02_faixa_valor: '',
                    t02_habilita_botao_ped_formar_carga: 'N',
                    t02_lang_user: null,
                    t02_envia_email_data_sincronizacao: 'N',
                    t02_perfil_transportadora: 'N'
                },
                {
                    t02_id: 14280,
                    t02_descricao: 'Marlon Ferreira da Silva',
                    t02_tipo: '1',
                    t02_login: 'marlon.silva',
                    t02_senha: '123Mudar',
                    t02_empresa_id: 271,
                    t02_perfil_id: 2904,
                    t02_codigo_erp: '',
                    t02_email: 'guilherme.guarnieri@rioquality.com.br',
                    t02_telefone: '21993840914',
                    t02_sn_exibe_help_campos: 'S',
                    t02_googleapi: 'P',
                    t02_primeiro_acesso: 'S',
                    t02_ordem_colunas_form_cargas: null,
                    t02_data_hora_atualizacao: null,
                    t02_filial_expedicao_padrao: null,
                    t02_filiais_fatura_padrao: null,
                    t02_situacao: 1,
                    t02_faixa_valor: '',
                    t02_habilita_botao_ped_formar_carga: 'N',
                    t02_lang_user: null,
                    t02_envia_email_data_sincronizacao: 'N',
                    t02_perfil_transportadora: 'N'
                },
                {
                    t02_id: 14532,
                    t02_descricao: 'Leonardo Sidral Louzada',
                    t02_tipo: '',
                    t02_login: 'leonardo.sidral',
                    t02_senha: '2501992235Crf',
                    t02_empresa_id: 271,
                    t02_perfil_id: 3090,
                    t02_codigo_erp: '',
                    t02_email: 'guilherme.guarnieri@rioquality.com.br',
                    t02_telefone: '',
                    t02_sn_exibe_help_campos: 'S',
                    t02_googleapi: 'P',
                    t02_primeiro_acesso: 'N',
                    t02_ordem_colunas_form_cargas: null,
                    t02_data_hora_atualizacao: null,
                    t02_filial_expedicao_padrao: 3428,
                    t02_filiais_fatura_padrao: '3428',
                    t02_situacao: 1,
                    t02_faixa_valor: '',
                    t02_habilita_botao_ped_formar_carga: 'N',
                    t02_lang_user: '',
                    t02_envia_email_data_sincronizacao: 'N',
                    t02_perfil_transportadora: 'N'
                }
            ]
    })
    console.log(result)
}

main();




